#!/usr/bin/env zsh

local ZERO="${(%):-%N}"
local BIN_DIR="${ZERO:h}"

# On asciinema 0 and ZERO are functionargzero
[[ "$BIN_DIR" = "." ]] && BIN_DIR="/usr/local/bin"

local SHARE_DIR="${BIN_DIR:h}/share"
source "$SHARE_DIR/giturl/script_preamble"
source "$SHARE_DIR/giturl/script_vars"
source "$SHARE_DIR/giturl/math_functions"
source "$SHARE_DIR/giturl/codes_huffman"
source "$SHARE_DIR/giturl/coding_functions"

ZKL_HELP="0"
ZKL_VERBOSE="-s"
ZKL_QUIET="0"
ZKL_NOANSI="0"
ZKL_REPO=""
local -A opthash
zparseopts -E -D -A opthash h -help v -verbose q -quiet n -noansi r: -repo: || exit 1

echo "Will parse: $1"
