#!/usr/bin/env zsh

local ZERO="${(%):-%N}"
local BIN_DIR="${ZERO:h}"

# On asciinema 0 and ZERO are functionargzero
[[ "$BIN_DIR" = "." ]] && BIN_DIR="/usr/local/bin"

local SHARE_DIR="${BIN_DIR:h}/share"

emulate -LR zsh

zmodload zsh/zutil

setopt extendedglob typesetsilent warncreateglobal

bindkey -e

local REPLY
local -a reply

builtin autoload -Uz colors
colors

# FUNCTION: SetMessage {{{
SetMessage() {
    echo "$1"
}
# }}}

# FUNCTION: PresentData {{{
PresentData() {
    local proto="$1" user="$2" site="$3" port="$4" upath="$5" rev="$6" file="$7"
    print "$fg[green]Protocol:$reset_color $proto"
    [[ -n "$user" ]] && print "$fg[green]User:$reset_color     $user"
    print "$fg[green]Site:$reset_color     $site"
    [[ -n "$port" ]] && print "$fg[green]Port:$reset_color     $port"
    print "$fg[yellow]Repo:$reset_color     $upath"
    [[ -n "$rev" ]] && print "$fg[yellow]Revision:$reset_color $rev"
    [[ -n "$file" ]] && print "$fg[red]File:$reset_color     $file"
}
# }}}

# vim:ft=zsh
